### ISSUE TITLE
Documentation Downloading Trust1Connector

### ISSUE THREAD

**Issue by louagej** [Trust1Team/t1c-sdk-js#9]
**Describe the bug**
Not all links for downloading the Trust1Connectors are working.

**To Reproduce**
1. Go to '[Documentation Downloading Trust1Connector](https://t1t.gitbook.io/t1c-js-guide-v3/core/downloading-latest-trust1connector#downloading-trust1connector)'
2. Copy the general link '[https://acc-ds.t1t.io/v3/downloads/installer](https://acc-ds.t1t.io/v3/downloads/installer)'
3. The response '....'

```json
{
success: false,
description: "Could not determine appropriate package for user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36",
code: 1010,
stackTrace: "models.DownloadException: Could not determine appropriate package for user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
	at controllers.DownloadController.$anonfun$downloadByUserAgent$1(DownloadController.scala:56)
	at security.UserAgentActionBuilder.$anonfun$invokeBlock$1(SecurityActionBuilders.scala:76)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
"
}
```

**Expected behavior**
The Distribution Service should analyse the User-Agent header and automatically initiate the download of an OS-appropriate installer of the latest configured version.

**Screenshots**
![image](https://user-images.githubusercontent.com/7229592/170251538-5f988cd3-6e09-41ad-ab61-c20a1f58885a.png)

**Desktop (please complete the following information):**
 - OS:
   - Edition: Windows 10 Pro
   - Version: 21H2
   - Installed on: ‎12/‎04/‎2022
   - OS build: 19044.1706

 - Browser: Chrome
 - Version: 101.0.4951.67 (Official Build) (64-bit)

**Additional context**

From The additional links, only the Mac links seems to work

1. https://acc-ds.t1t.io/v3/downloads/installer/win64 → Not working
2. https://acc-ds.t1t.io/v3/downloads/installer/win32 → Not working
3. https://ds.t1t.io/v3/downloads/installers/macos → OK
4. https://ds.t1t.io/v3/downloads/installers/macosarm → OK

**Comment by KrakenTyio** [comment]
looks like auto detect with `/donwload/install` it raise same error to not possible determine which version to download

**Comment by GillesPl** [comment]
Hello louagej, this could be related to the issue in the Distribution service where, like KrakenTyio mentioned, it uses an autodetect feature based on the user-agent header.

In our latest release of the Distribution service this should have been resolved. In any case this endpoint still remains a best effort. 

I've noticed in the links you provide, for windows the URL is different, it goes to `downloads/installer` and should be `download/installers`, and 3.0.0 until 3.4.x has been deprecated as we've rewritten te Connector completely. We now have v3_5 as a base --> `https://acc-ds.t1t.io/v3_5/downloads/installers/:os` where :os can be `win64` `win32` `macos` `macosarm` 

As described in [this page in our documentation](https://t1t.gitbook.io/t1c-js-v3.7.x/core/downloading-latest-trust1connector#example-upgrade-flow) you can also fetch the latest version info from the DS and use the direct links where the releases are stored.
With this you can provide either a fallback if the `/download/installers` fails or creat your own custom implementation to select the correct version to download
